### ISSUE TITLE
Why isnt there a release?

### ISSUE THREAD

**Issue by Pdzly** [VanderCat/GmodMenuRemake#2]

**Comment by VanderCat** [comment]
I'll make them in future. For now you need to compile it (it's easier than compile c code though) or if you don't wanna compile you can clone the `github-pages` branch and install it by instctructions on `main` branch. (it may have junk js files)

**Comment by VanderCat** [comment]
`gh-pages` is now built automaticly each push, so you dont even need to compile now. Still be aware of junk.js<sup>TM</sup>
