### ISSUE TITLE
hoow do you install this

### ISSUE THREAD

**Issue by thiccelf83** [VanderCat/GmodMenuRemake#5]
This is in some obscure file format and not in any directory structure ive seen in menu replacements/gmod addons.

Unless its not installable and has to be built? In which case this is just trash

**Comment by VanderCat** [comment]
1. download zip from https://github.com/VanderCat/GmodMenuRemake/tree/gh-pages
2. place it in `steamapps/common/GarrysMod/garrysmod/html/ANY_NAME`
3. edit 24th line in `steamapps/common/GarrysMod/garrysmod/lua/mainmenu.lua`:
    ```diff
    @@ 24,-1 24, +1 @@
    -self.HTML:OpenURL( "asset://garrysmod/html/menu.html" )
    +self.HTML:OpenURL( "asset://garrysmod/html/ANY_NAME/index.html" )
    ```
4. launch gmod

to disable the menu revert changes in `mainmanu.lua` or verify game files
